server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rag
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true